name: teamtrack
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 5.0.0+6

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  provider: ^5.0.0
  uuid: ^3.0.4
  tuple: ^2.0.0
  shared_preferences: ^2.0.6
  fluttercontactpicker: ^4.5.1
  url_launcher: ^6.0.6
  date_format: ^2.0.4
  location: ^4.3.0
  rxdart: ^0.27.2
  google_maps_cluster_manager: ^3.0.0+1

  google_fonts: ^2.1.0
  curved_navigation_bar: ^1.0.1
  assorted_layout_widgets: ^5.2.1
  fl_chart: ^0.36.1
  flutter_slidable: ^0.6.0
  auth_buttons: ^1.0.1+3
  syncfusion_flutter_charts: ^19.1.67
  google_maps_flutter: ^2.1.0

  firebase_core: ^1.7.0
  # firebase_dynamic_links: ^2.0.4
  firebase_remote_config: ^0.11.0+1
  firebase_auth: ^3.1.2
  cloud_firestore: ^2.5.3
  cloud_functions: ^3.0.4
  # firebase_analytics: ^8.1.0
  firebase_database: ^8.0.1
  google_sign_in: ^5.1.1
  firebase_messaging: ^10.0.2
  geoflutterfire: ^3.0.1

  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  flutter_native_splash: ^1.1.8+4
  flutter_local_notifications: ^6.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter
flutter_icons:
  image_path_android: "lib/icon.jpg"
  image_path_ios: "lib/icon.jpg"
  ios: true 

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: Revival
      fonts:
        - asset: assets/fonts/Revival_Modern.otf
    - family: Revival Gothic
      fonts:
        - asset: assets/fonts/Revival_Gothic.otf
  assets:
    - assets/images/LoadingScreen.png
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
